on: [ push, pull_request ]
jobs:
  macos:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [ 8, 11, 16 ]
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: ${{ matrix.java }}
      - uses: actions/gradle-cache@v1
        with:
          job-id: ${{ matrix.os }}-j${{ matrix.java }}
          arguments: check
